# Topic Modelling - LDA & NMF 

In [1]:
import numpy as np
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english')

In [6]:
dtm = cv.fit_transform(npr['Article'])

In [7]:
from sklearn.decomposition import LatentDirichletAllocation

In [8]:
LDA = LatentDirichletAllocation(n_components=7, random_state=42)

In [9]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

# Grab the vocab

In [16]:
len(cv.get_feature_names())

54777

In [17]:
type(cv.get_feature_names())

list

In [24]:
import random

random_word_id = random.randint(0,222)

cv.get_feature_names()[random_word_id]
                     

'136'

# Grab the Topics

In [32]:
len(LDA.components_)

7

In [29]:
LDA.components_[0]

array([8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
       1.43006821e-01, 1.42902042e-01, 1.42861626e-01])

In [30]:
single_topic = LDA.components_[0]

In [33]:
top_ten_words = single_topic.argsort()[-10:]

In [34]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


# Grab the highest probablity words per Topic

In [38]:
for i, topic in enumerate(LDA.components_):
    print(f"TOP 15 WORDS FROM THE TOPIC #{i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print ('\n')
    print ('\n')

TOP 15 WORDS FROM THE TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




TOP 15 WORDS FROM THE TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




TOP 15 WORDS FROM THE TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




TOP 15 WORDS FROM THE TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




TOP 15 WORDS FROM THE TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




TOP 15 WORDS FROM THE TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 

# Add the topics in the dataset

In [39]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [40]:
topic_results = LDA.transform(dtm)

In [41]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0], dtype=int64)

In [43]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [44]:
npr['Topic Number'] = topic_results.argmax(axis=1)

In [45]:
npr.head()

Article  Topic Number
0  In the Washington of 2016, even when the polic...             1
1    Donald Trump has used Twitter  —   his prefe...             1
2    Donald Trump is unabashedly praising Russian...             1
3  Updated at 2:50 p. m. ET, Russian President Vl...             1
4  From photography, illustration and video, to d...             2

In [46]:
my_dict = { 0: 'Tango', 1:'Charlie', 2:'Leema', 3:'Alpha',4:'Beta',5:'Siera',6:'Dixxy',7:'Liona'}

In [49]:
npr['Topic Label'] = npr['Topic Number'].map(my_dict)

In [50]:
npr.head(20)

Article  Topic Number  \
0   In the Washington of 2016, even when the polic...             1   
1     Donald Trump has used Twitter  —   his prefe...             1   
2     Donald Trump is unabashedly praising Russian...             1   
3   Updated at 2:50 p. m. ET, Russian President Vl...             1   
4   From photography, illustration and video, to d...             2   
5   I did not want to join yoga class. I hated tho...             3   
6   With a   who has publicly supported the debunk...             3   
7   I was standing by the airport exit, debating w...             2   
8   If movies were trying to be more realistic, pe...             3   
9   Eighteen years ago, on New Year’s Eve, David F...             2   
10  For years now, some of the best, wildest, most...             5   
11  For years now, some of the best, wildest, most...             5   
12  The Colorado River is like a giant bank accoun...             2   
13  For the last installment of NPR’s holiday reci...             2   
14  Being overweight can raise your blood pressure...             3   
15  Who’s the YouTube star of 2016? Adele singing ...             5   
16  Here’s a quick roundup of some of the   you ma...             2   
17  Ben Johnston doesn’t follow the rules of music...             5   
18  David Bowie, Prince and George Michael are all...             5   
19  In November, the typically straitlaced Office ...             1   

   Topic Label  
0      Charlie  
1      Charlie  
2      Charlie  
3      Charlie  
4        Leema  
5        Alpha  
6        Alpha  
7        Leema  
8        Alpha  
9        Leema  
10       Siera  
11       Siera  
12       Leema  
13       Leema  
14       Alpha  
15       Siera  
16       Leema  
17       Siera  
18       Siera  
19     Charlie